-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 00:10:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cargas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cargas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cargas` DEFAULT CHARACTER SET utf8 ;
USE `cargas` ;

-- -----------------------------------------------------
-- Table `cargas`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Pais` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Estado` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Pais_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Estado_Pais_idx` (`Pais_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_Pais`
    FOREIGN KEY (`Pais_Id`)
    REFERENCES `cargas`.`Pais` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Cidade` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Estado_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_Id`)
    REFERENCES `cargas`.`Estado` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Localizacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Localizacoes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `PossuiPorto` VARCHAR(45) NULL,
  `Cidade_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Localizacoes_Cidade1_idx` (`Cidade_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Localizacoes_Cidade1`
    FOREIGN KEY (`Cidade_Id`)
    REFERENCES `cargas`.`Cidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Status_Cargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Status_Cargas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Marcas_Camioes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Marcas_Camioes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Camioes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Camioes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Placa` VARCHAR(10) NULL,
  `Capacidade_de_Carga` INT NULL,
  `Marcas_Camioes_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Camioes_Marcas_Camioes1_idx` (`Marcas_Camioes_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Camioes_Marcas_Camioes1`
    FOREIGN KEY (`Marcas_Camioes_Id`)
    REFERENCES `cargas`.`Marcas_Camioes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Funcionarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Ci` INT(11) NULL,
  `Nome` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Controladores_Cargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Controladores_Cargas` (
  `Licenca` INT(12) NULL,
  `Funcionarios_Id` INT NOT NULL,
  CONSTRAINT `fk_Controladores Cargas_Funcionarios1`
    FOREIGN KEY (`Funcionarios_Id`)
    REFERENCES `cargas`.`Funcionarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Motoristas_Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Motoristas_Categorias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Motorista` (
  `Numero_Carteira_Motorista` INT(12) NULL,
  `Funcionarios_Id` INT NOT NULL,
  `Motoristas_Categorias_Id` INT NOT NULL,
  INDEX `fk_Motorista_Motoristas_Categorias1_idx` (`Motoristas_Categorias_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Motorista_Funcionarios1`
    FOREIGN KEY (`Funcionarios_Id`)
    REFERENCES `cargas`.`Funcionarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Motorista_Motoristas_Categorias1`
    FOREIGN KEY (`Motoristas_Categorias_Id`)
    REFERENCES `cargas`.`Motoristas_Categorias` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Cargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Cargas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Data_Saida` DATE NULL,
  `Hora_Saida` TIME NULL,
  `Data_Chegada` DATE NULL,
  `Hora_Chegada` TIME NULL,
  `Origem` INT NOT NULL,
  `Destino` INT NOT NULL,
  `Status_Cargas_Id` INT NOT NULL,
  `Camioes_Id` INT NOT NULL,
  `Controlador_Id` INT NOT NULL,
  `Motorista_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Cargas_Localizacoes1_idx` (`Origem` ASC) VISIBLE,
  INDEX `fk_Cargas_Localizacoes2_idx` (`Destino` ASC) VISIBLE,
  INDEX `fk_Cargas_Status Cargas1_idx` (`Status_Cargas_Id` ASC) VISIBLE,
  INDEX `fk_Cargas_Camioes1_idx` (`Camioes_Id` ASC) VISIBLE,
  INDEX `fk_Cargas_Controladores Cargas1_idx` (`Controlador_Id` ASC) VISIBLE,
  INDEX `fk_Cargas_Motorista1_idx` (`Motorista_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Cargas_Localizacoes1`
    FOREIGN KEY (`Origem`)
    REFERENCES `cargas`.`Localizacoes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Localizacoes2`
    FOREIGN KEY (`Destino`)
    REFERENCES `cargas`.`Localizacoes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Status Cargas1`
    FOREIGN KEY (`Status_Cargas_Id`)
    REFERENCES `cargas`.`Status_Cargas` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Camioes1`
    FOREIGN KEY (`Camioes_Id`)
    REFERENCES `cargas`.`Camioes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Controladores Cargas1`
    FOREIGN KEY (`Controlador_Id`)
    REFERENCES `cargas`.`Controladores_Cargas` (`Funcionarios_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Motorista1`
    FOREIGN KEY (`Motorista_Id`)
    REFERENCES `cargas`.`Motorista` (`Funcionarios_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Tipos_Madeiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Tipos_Madeiras` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargas`.`Cargas_Madeiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargas`.`Cargas_Madeiras` (
  `Peso` INT NULL,
  `Tipos_Madeiras_Id` INT NOT NULL,
  `Cargas_Id` INT NOT NULL,
  INDEX `fk_Cargas Madeiras_Tipos Madeiras1_idx` (`Tipos_Madeiras_Id` ASC) VISIBLE,
  INDEX `fk_Cargas Madeiras_Cargas1_idx` (`Cargas_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Cargas Madeiras_Tipos Madeiras1`
    FOREIGN KEY (`Tipos_Madeiras_Id`)
    REFERENCES `cargas`.`Tipos_Madeiras` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas Madeiras_Cargas1`
    FOREIGN KEY (`Cargas_Id`)
    REFERENCES `cargas`.`Cargas` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/* Comandos Funcionarios */

INSERT INTO Funcionarios (Ci,Nome,Telefone) VALUES ('123456767','Jorge','3243322');
INSERT INTO Funcionarios (Ci,Nome,Telefone) VALUES ('120897877','Joao','3253332');

/*SELECT * FROM Funcionarios;*/

UPDATE Funcionarios SET Ci='5765',Nome = 'Josevaldo' WHERE Id=1;

/*DELETE FROM Funcionarios WHERE Id=1;*/

/* Comandos Marcas_Camioes */

INSERT INTO Marcas_Camioes (Nome) VALUES ('Scania');

/*SELECT * FROM Marcas_Camioes;*/

UPDATE Marcas_Camioes SET Nome='0',Nome = 'Mack' WHERE Id=1;

/* DELETE FROM Marcas_Camioes WHERE Id=1; */

/* Comandos Camioes */

INSERT INTO Camioes (Placa,Capacidade_de_Carga,Marcas_Camioes_Id) VALUES ('123456767','2',1);

/*SELECT * FROM Camioes;*/

UPDATE Camioes SET Placa='8767657', Capacidade_de_Carga='3', Marcas_Camioes_Id='1' WHERE Id=1;

/* DELETE FROM Camioes WHERE Id=1; */

/* Comandos Pais */

INSERT INTO Pais(Nome) VALUES ('Brasil');

/*SELECT * FROM Pais;*/

UPDATE Pais SET Nome='Brezil' WHERE Id=1;

/* DELETE FROM Pais WHERE Id=1; */

/* Comandos Estado */

INSERT INTO Estado (Nome,Pais_Id) VALUES ('Rio Grande do Sul',1);

/*SELECT * FROM Estado;*/

UPDATE Estado SET Nome='RS' WHERE Id=1;

/* DELETE FROM Estado WHERE Id=1; */

/* Comandos Cidade */

INSERT INTO Cidade (Nome,Estado_Id) VALUES ('Santana do Livramento',1);
INSERT INTO Cidade (Nome,Estado_Id) VALUES ('Bage',1);

/*SELECT * FROM Cidade;*/

UPDATE Cidade SET Nome='Santana' WHERE Id=1;

/* DELETE FROM Cidade WHERE Id=1; */

/* Comandos Controladores */

INSERT INTO Controladores_Cargas (Licenca,Funcionarios_Id) VALUES (1322444,1);

/*SELECT * FROM Controladores_Cargas;*/

UPDATE Controladores_Cargas SET Licenca='3445566' WHERE Funcionarios_Id=1;

/* DELETE FROM Controladores_Cargas WHERE Id=1; */

/* Comandos Motoristas_Categorias */

INSERT INTO Motoristas_Categorias(Nome) VALUES ('A');

/*SELECT * FROM Motoristas_Categorias*;*/

UPDATE Motoristas_Categorias SET Nome='B' WHERE Id=1;

/* DELETE FROM Motoristas_Categorias WHERE Id=1; */

/* Comandos  Motorista*/

INSERT INTO Motorista(Numero_Carteira_Motorista,Funcionarios_Id,Motoristas_Categorias_Id)
VALUES ('47634765',2,1);

/*SELECT * FROM Motorista;*/

UPDATE Motorista SET Numero_Carteira_Motorista="786757645" WHERE Funcionarios_Id=2;

/* DELETE FROM  Motorista WHERE Id_Funcionario=1; */

/* Comandos Tipos_Madeiras */

INSERT INTO Tipos_Madeiras(Nome) VALUES ('Eucalipte');

/*SELECT * FROM Tipos_Madeiras ; */

UPDATE Tipos_Madeiras SET Nome="Eucalipto" WHERE Id=1;

/* DELETE FROM Tipos_Madeiras WHERE Id=1; */

/* Comandos  Localizacoes*/

INSERT INTO Localizacoes(Nome,PossuiPorto,Cidade_Id) VALUES ('EcoPoint',0,1);

/*SELECT * FROM Localizacoes;*/

UPDATE  Localizacoes SET Nome='EcoPonto' WHERE Id=1;

/* DELETE FROM Localizacoes WHERE Id=1; */

/* Comandos  Status_Cargas*/

INSERT INTO Status_Cargas (Nome) VALUES ('Ok');

/*SELECT * FROM Status_Cargas;*/

UPDATE Status_Cargas SET Nome="Bom" WHERE Id=1;

/* DELETE FROM Status_Cargas  WHERE Id=1; */

/* Comandos  Cargas*/

INSERT INTO Cargas(Data_Saida,Hora_Saida,Data_Chegada,Hora_Chegada,Origem,Destino,
Status_cargas_Id,Camioes_Id,Controlador_Id,Motorista_Id)
VALUES ('2020-12-11','1','2020-10-11','3',1,2,1,1,1,2);

SELECT * FROM Cargas;

UPDATE  Cargas SET Data_Chegada='2020-12-11' WHERE Id=1;

/* DELETE FROM Cargas WHERE Id=1; */

/* Comandos  Cargas_Madieras*/

INSERT INTO Cargas_Madeiras(Peso,Tipos_Madeiras_Id,Cargas_Id) VALUES (20,1,1);

/*SELECT * FROM Cargas_Madeiras;*/

UPDATE Cargas_Madeiras SET Peso=30 WHERE Cargas_Id=1 and Tipos_Madeiras_Id=1;

/* DELETE FROM  WHERE Id=1; */


DROP DATABASE cargas;
