-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 00:10:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Pais_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Estado_Pais_idx` (`Pais_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_Pais`
    FOREIGN KEY (`Pais_Id`)
    REFERENCES `mydb`.`Pais` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Estado_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_Id`)
    REFERENCES `mydb`.`Estado` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Localizacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Localizacoes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Possui Porto` VARCHAR(45) NULL,
  `Cidade_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Localizacoes_Cidade1_idx` (`Cidade_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Localizacoes_Cidade1`
    FOREIGN KEY (`Cidade_Id`)
    REFERENCES `mydb`.`Cidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status_Cargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status_Cargas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marcas_Camioes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marcas_Camioes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Camioes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Camioes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Placa` VARCHAR(10) NULL,
  `Capacidade_de_Carga` INT NULL,
  `Marcas_Camioes_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Camioes_Marcas_Camioes1_idx` (`Marcas_Camioes_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Camioes_Marcas_Camioes1`
    FOREIGN KEY (`Marcas_Camioes_Id`)
    REFERENCES `mydb`.`Marcas_Camioes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Ci` INT(11) NULL,
  `Nome` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Controladores_Cargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Controladores_Cargas` (
  `Licenca` INT(12) NULL,
  `Funcionarios_Id` INT NOT NULL,
  CONSTRAINT `fk_Controladores Cargas_Funcionarios1`
    FOREIGN KEY (`Funcionarios_Id`)
    REFERENCES `mydb`.`Funcionarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Motoristas_Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Motoristas_Categorias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Motorista` (
  `Numero_Carteira_Motorista` INT(12) NULL,
  `Funcionarios_Id` INT NOT NULL,
  `Motoristas Categorias_Id` INT NOT NULL,
  INDEX `fk_Motorista_Motoristas Categorias1_idx` (`Motoristas Categorias_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Motorista_Funcionarios1`
    FOREIGN KEY (`Funcionarios_Id`)
    REFERENCES `mydb`.`Funcionarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Motorista_Motoristas Categorias1`
    FOREIGN KEY (`Motoristas Categorias_Id`)
    REFERENCES `mydb`.`Motoristas_Categorias` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Data_Saida` DATE NULL,
  `Hora_Saida` TIME NULL,
  `Data_Chegada` DATE NULL,
  `Hora_Chegada` TIME NULL,
  `Origem` INT NOT NULL,
  `Destino` INT NOT NULL,
  `Status Cargas_Id` INT NOT NULL,
  `Camioes_Id` INT NOT NULL,
  `Controlador_Id` INT NOT NULL,
  `Motorista_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Cargas_Localizacoes1_idx` (`Origem` ASC) VISIBLE,
  INDEX `fk_Cargas_Localizacoes2_idx` (`Destino` ASC) VISIBLE,
  INDEX `fk_Cargas_Status Cargas1_idx` (`Status Cargas_Id` ASC) VISIBLE,
  INDEX `fk_Cargas_Camioes1_idx` (`Camioes_Id` ASC) VISIBLE,
  INDEX `fk_Cargas_Controladores Cargas1_idx` (`Controlador_Id` ASC) VISIBLE,
  INDEX `fk_Cargas_Motorista1_idx` (`Motorista_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Cargas_Localizacoes1`
    FOREIGN KEY (`Origem`)
    REFERENCES `mydb`.`Localizacoes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Localizacoes2`
    FOREIGN KEY (`Destino`)
    REFERENCES `mydb`.`Localizacoes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Status Cargas1`
    FOREIGN KEY (`Status Cargas_Id`)
    REFERENCES `mydb`.`Status_Cargas` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Camioes1`
    FOREIGN KEY (`Camioes_Id`)
    REFERENCES `mydb`.`Camioes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Controladores Cargas1`
    FOREIGN KEY (`Controlador_Id`)
    REFERENCES `mydb`.`Controladores_Cargas` (`Funcionarios_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas_Motorista1`
    FOREIGN KEY (`Motorista_Id`)
    REFERENCES `mydb`.`Motorista` (`Funcionarios_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipos_Madeiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipos_Madeiras` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargas_Madeiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargas_Madeiras` (
  `Peso` INT NULL,
  `Tipos Madeiras_Id` INT NOT NULL,
  `Cargas_Id` INT NOT NULL,
  INDEX `fk_Cargas Madeiras_Tipos Madeiras1_idx` (`Tipos Madeiras_Id` ASC) VISIBLE,
  INDEX `fk_Cargas Madeiras_Cargas1_idx` (`Cargas_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Cargas Madeiras_Tipos Madeiras1`
    FOREIGN KEY (`Tipos Madeiras_Id`)
    REFERENCES `mydb`.`Tipos_Madeiras` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargas Madeiras_Cargas1`
    FOREIGN KEY (`Cargas_Id`)
    REFERENCES `mydb`.`Cargas` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
